experiment_name: Tissue1
global_parameters_for_this_experiment:
  glycan_dataset: df_tissue
  glycan_class: tissue_sample
  num_runs: 10
  epochs: 150
  batch_size: 128
  train_size: 0.7
  learning_rate: 0.005
  drop_last: false
  augment_prob: 0.0
  generaliz_prob: 0.2
  patience: 25
experiment_specific_configs:
  name: Tissue1
  glycan_dataset: df_tissue
  glycan_class: tissue_sample
all_model_configurations_tested:
- name: baseline_trainable
  initialization_method: random
  trainable_embeddings: true
- name: baseline_fixed
  initialization_method: random
  trainable_embeddings: false
- name: infused_trainable
  initialization_method: external
  trainable_embeddings: true
- name: infused_fixed
  initialization_method: external
  trainable_embeddings: false
base_random_state_for_experiment_batch: 42
